blueprint:
  name: Switch alternativi
  description: Rende due switch alternativi
  domain: automation
  input:
    switchList:
      name: List of switches
      selector:
        entity:
          domain: switch
          multiple: true
variables:
  switches: !input switchList
trigger:
  - platform: state
    entity_id: !input switchList
    to: "on"
action:
  - service: switch.turn_off
    target:
      entity_id:
        - switch.schedule_parents_absence_quo
        - '{{ expand(switches) | selectattr("entity_id", "!=", trigger.entity_id) | map(attribute="entity_id") | list }}'
mode: single
