blueprint:
  name: Switch alternativi beta 8
  description: Rende due switch alternativi
  domain: automation
  
  input:
  
    absence:
      name: Schedule mode absence
      description: Entité générée par Scheduler pour la planification du mode absence (switch)
      selector:
        entity:
          domain: switch
          
    switchList:
      name: List of switches
      selector:
        entity:
          domain: switch
          multiple: true
          
trigger_variables:
  ARRET:
    - !input absence
    - !input switchList
  
trigger:
  - platform: state
    entity_id: ARRET
    to: "on"
action:
  - service: switch.turn_off
    target:
      entity_id: '{{ expand(ARRET) | selectattr("entity_id", "!=", trigger.entity_id) | map(attribute="entity_id") | list }}'

mode: single
